<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function mslmsstartertheme_child_enqueue_styles() {
    wp_enqueue_style( 'ms-lms-starter-theme-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'ms-lms-starter-theme-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'ms-lms-starter-theme-style' ),
        wp_get_theme()->get('Version')
    );

	wp_enqueue_style( 'ms-lms-starter-theme-index-style',
        get_stylesheet_directory_uri() . '/assets/css/index.css',
        array(  ),
        time()
    );
	wp_enqueue_style( 'ms-lms-starter-theme-global-style',
        get_stylesheet_directory_uri() . '/assets/css/global.css',
        array(  ),
        time()
    );

}

add_action(  'wp_enqueue_scripts', 'mslmsstartertheme_child_enqueue_styles' );

function add_google_fonts() {
    wp_enqueue_style( 'roboto-font', 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap', false );
    wp_enqueue_style( 'poppins-font', 'https://fonts.googleapis.com/css2?family=Poppins:wght@600;700&display=swap', false );
    wp_enqueue_style( 'poppins-semibold-font', 'https://fonts.googleapis.com/css2?family=Poppins+SemiBold:wght@400&display=swap', false );
    wp_enqueue_style( 'inter-font', 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap', false );
}
add_action( 'wp_enqueue_scripts', 'add_google_fonts' );



if ( ! function_exists( 'stm_module_styles' ) ) {
	function stm_module_styles( $handle, $style = 'style_1', $deps = array(), $inline_styles = '' ) {
		if ( stm_lms_is_masterstudy_theme() ) {
			$path   = get_template_directory_uri() . '/assets/css/vc_modules/' . $handle . '/' . $style . '.css';
			$handle = 'stm-' . $handle . '-' . $style;
			wp_enqueue_style( $handle, $path, $deps, STM_LMS_VERSION, 'all' );
			if ( ! empty( $inline_styles ) ) {
				wp_add_inline_style( $handle, $inline_styles );
			}
		}
	}
}